### ISSUE TITLE
Exception error while running example

### ISSUE THREAD

**Issue by lafpi** [DanielCardonaRojas/verify#1]
Hi I got the following Exception error on line 39 (final Either...) of the sample project.

`_TypeError (type 'Left<List<ValidationError>, User>' is not a subtype of type 'Either<List<Error>, User>')`

Do you have any clue? I am running on Dart 2.7.

Regards,
Pierre

**Comment by lafpi** [comment]
Hi, I replaced the Error class with the ValidationError class and it fixed the problem. I don't know if casting will cause any side effects though. Vraisemblablement

```
39-40  final Either<List<Error>, User> validationResult =
             userValidator.verify(someUser);
```
changed to:

```
39-40  final Either<List<ValidationError>, User> validationResult =
             userValidator.verify(someUser);
```

Now, I can appreciate the good code that you write.

Regards,
Pierre

**Comment by DanielCardonaRojas** [comment]
Hi @lafpi, thank you for taking the time trying out this package. I've released a new version of the package with better documentation and completely replaced the sample project for a more elaborate one.

All custom error types should implement ValidationError.

I've also put together a small article about the sample project, it its useful:

https://dev.to/danielcardonarojas/form-validations-with-bloc-verify-1aib

**Comment by lafpi** [comment]
Thanks for taking time to respond. I will give it a try.

Pierre
